webshop/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from webshop import settings
from app.views import *

urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^$', index, name='index'),
    url(r'^news$', news, name='news'),
    url(r'^search$', search, name='search'),
    url(r'^about$', about, name='about'),
    url(r'^brands$', brands, name='brands'),
    url(r'^contacts$', contacts, name='contacts'),
    url(r'^alinex$', alinex, name='alinex'),
    url(r'^alinapaint$', alina_paint, name='alina_paint'),
    url(r'^nashi$', nashi, name='nashi'),
    url(r'^trade/(?P<id>\d+)$', trade, name='trade'),
    url(r'^basket$', basket, name='basket'),
    url(r'^basket/add/(?P<trade_id>\d+)$', add_to_basket, name='add_to_basket'),
    url(r'^basket/remove$', remove_from_basket, name='remove_from_basket'),
    url(r'^basket/update/(?P<trade_id>\d+)$', update_basket, name='update_basket'),
    url(r'^basket/all$', list_basket_items, name='list_basket_items'),
    url(r'^basket/clear$', clear_basket, name='clear_basket'),
    url(r'^basket/count/total/price/$', count_basket_cost, name='count_basket_total_price'),
    url(r'^basket/pay/prepare/$', payment_preparing, name='payment_preparing'),
    url(r'^basket/pay/cash/$', pay_money, name='payment_cash'),
    url(r'^basket/pay/result$', payment_preparing, name='payment_preparing'),
    url(r'^calculator/category/(?P<category_id>\d+)/$', calculator, name='calculator'),
    url(r'^category/(?P<category_id>\d+)/$', category, name='category'),
    url(r'^category/(?P<category_id>\d+)/(?P<sub_category_id>\d+)/$', category, name='sub_category'),
    url(r'^misc/trade/add/$', temp_trade_add_view, name='temp_trade_add'),
    url(r'^upload/trade$', upload_trade_data, name='upload_trade_data'),
    url(r'^ajax/index/paginate$', ajax_index_pagination, name='index_paginate'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_models/models.py
# coding=utf-8
from __future__ import unicode_literals
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User as BaseUser
from django.db import models

# Create your models here.


class Category(models.Model):
    class Meta:
        verbose_name_plural = 'Категории'
        verbose_name = 'Категория'

    title = models.CharField(verbose_name='Название', max_length=255, unique=False, null=False)
    parent_category = models.ForeignKey(verbose_name='Родительская категория', to='Category', on_delete=models.CASCADE,
                                        null=True, blank=True)
    type = models.CharField(verbose_name='Раздел категории', choices=(
        ('construction', 'Строительные материалы'), ('decoration', 'Отделочные материалы'),
        ('tools', 'Инструменты')
    ), max_length=255, null=True)
    description = models.CharField(max_length=255, verbose_name='Описание категории', null=True, blank=True)

    created_at = models.DateTimeField(verbose_name='Создано', auto_now_add=True, null=True)
    updated_at = models.DateTimeField(verbose_name='Обновлено', auto_now=True, null=True)

    def __unicode__(self):
        return self.title


class Trade(models.Model):
    class Meta:
        db_table = 'trade'
        verbose_name_plural = 'Товары'
        verbose_name = 'Товар'

    article = models.CharField(verbose_name='Артикул', max_length=255, null=True, blank=True)
    title = models.CharField(verbose_name='Название', max_length=255, unique=False, null=False)
    description = RichTextUploadingField(verbose_name='Описание', null=True, blank=True)
    short_description = RichTextUploadingField(verbose_name='Краткое описание', null=True, blank=True)
    instruction = RichTextUploadingField(verbose_name='Инструкция', null=True, blank=True)
    properties = RichTextUploadingField(verbose_name='Свойства', null=True, blank=True)
    price_settings = models.ManyToManyField('PriceWeight', verbose_name='Цена')
    is_visible = models.BooleanField(verbose_name='Видим?', null=False)
    category = models.ForeignKey(verbose_name='Категория', to=Category, on_delete=models.CASCADE, null=True)
    discount = models.IntegerField(verbose_name='Скидка', default=0)
    image = models.ImageField(verbose_name='Изображение', null=True, blank=True, upload_to='images')
    brand = models.CharField(verbose_name='Бренд', max_length=255, choices=(
        ('alinex', 'Alinex'), ('nashi', 'Наши'), ('alinapaint', 'Alina Paint')
    ), null=True)
    consumption = models.FloatField(verbose_name='Расход (на единицу кв.м.)', default=0)
    layer_weight = models.FloatField(verbose_name='Расходная толщина (мм.)', default=0)
    product_code = models.CharField(verbose_name='Код товара', max_length=255, null=True, blank=True)

    created_at = models.DateTimeField(verbose_name='Создано', auto_now_add=True, null=True)
    updated_at = models.DateTimeField(verbose_name='Об  новлено', auto_now=True, null=True)

    def __unicode__(self):
        return self.title


class User(BaseUser):
    class Meta:
        verbose_name = 'Пользователи'
        verbose_name_plural = 'Пользователи'


class Order(models.Model):
    class Meta:
        verbose_name_plural = 'Заказы'
        verbose_name = 'Заказ'

    elements = models.TextField(verbose_name='Элементы заказа', null=False, default='Заказы:')
    sum = models.FloatField(verbose_name='Сумма', null=False)
    accepted = models.BooleanField(verbose_name='Принято', default=False)
    delivered = models.BooleanField(verbose_name='Доставлено', default=False)
    
    created_at = models.DateTimeField(verbose_name='Создано', auto_now_add=True, null=True)
    updated_at = models.DateTimeField(verbose_name='ОБновлено', auto_now=True, null=True)

    def __unicode__(self):
        return '%s - %s' % (self.user.username, self.sum)


class OrderItem(models.Model):
    class Meta:
        verbose_name_plural = 'Элементы заказов'
        verbose_name = 'Элемент заказа'

    trade = models.ForeignKey(verbose_name='Товар', to=Trade, on_delete=models.CASCADE, null=False)
    quantity = models.IntegerField(verbose_name='Количество', null=False)
    order = models.ForeignKey(verbose_name='Заказ', to=Order, on_delete=models.CASCADE, null=False)
    
    created_at = models.DateTimeField(verbose_name='Создано', auto_now_add=True, null=True)
    updated_at = models.DateTimeField(verbose_name='Обновлено', auto_now=True, null=True)

    def __unicode__(self):
        return '%s - %s' % (self.trade.title, self.quantity)


class News(models.Model):
    class Meta:
        verbose_name_plural = 'Новости'
        verbose_name = 'Новости'

    title = models.CharField(verbose_name='Заголовок', max_length=255, unique=False, null=False)
    description = RichTextUploadingField(verbose_name='Описание категории', null=True, blank=True)
    is_visible = models.BooleanField(verbose_name='Видим?', null=False)
    
    created_at = models.DateTimeField(verbose_name='Создано', auto_now_add=True, null=True)
    updated_at = models.DateTimeField(verbose_name='Обновлено', auto_now=True, null=True)

    def __unicode__(self):
        return self.title


class PriceWeight(models.Model):
    class Meta:
        verbose_name_plural = 'Цены'
        verbose_name = 'Цена'

    weight = models.CharField(verbose_name='Вес', max_length=255, unique=False, null=False)
    price = models.FloatField(verbose_name='Цена', null=False)
    
    created_at = models.DateTimeField(verbose_name='Создано', auto_now_add=True, null=True)
    updated_at = models.DateTimeField(verbose_name='Обновлено', auto_now=True, null=True)

    def __unicode__(self):
        return '%s кг - %s руб' % (self.weight, self.price)


class PageContent(models.Model):
    class Meta:
        db_table = 'page_content'
        verbose_name = 'Редактрование страниц'
        verbose_name_plural = 'Редактирование страниц'

    about = RichTextUploadingField(verbose_name='О нас', null=True, blank=True)
    contacts = RichTextUploadingField(verbose_name='Контакты', null=True, blank=True)
    alinex = RichTextUploadingField(verbose_name='Alinex', null=True, blank=True)
    alina_paint = RichTextUploadingField(verbose_name='Alina Paint', null=True, blank=True)
    nashi = RichTextUploadingField(verbose_name='Nashi', null=True, blank=True)

    def __unicode__(self):
        return 'Редактирование страниц: "О нас", "Контакты" и страница брендов'

templates/app/about.html
{% extends "base.html" %}
{% block title %}
    О компании
{% endblock %}

{% block body_wrapper_begin %}{% endblock %}
{% block body_wrapper_end %}{% endblock %}

{% block main_content %}
    <div class="about-content">
        <div class="wrapper">
            <div class="about">
                <h1>О компании</h1>

                <p>
                    {{ content|safe }}
                </p>

                <div class="mission">
                    <h2>Миссия</h2>

                    <p>Мы создаем строительные материалы, которые преображают Жизнь каждого Человека и обеспечивают
                        Безопасность, Комфорт и Уверенность в будущем.</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block footer_content %}
{% endblock %}

templates/app/basket.html
{% extends "base.html" %}
{% block title %}
    Корзина
{% endblock %}

{% block main_content %}
    <div class="basket-content">
        <div class="basket-wrapper">
            <h1>Моя корзина</h1>
            <div class="basket-main">
                <div class="new-table">
                    <table>
                        <colgroup>
                            <col class="col1">
                        </colgroup>
                        <thead>
                        <tr>
                            <th scope="col">Название</th>
                            <th scope="col">Объем</th>
                            <th scope="col">Количество</th>
                            <th scope="col">Цена</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% include 'app/partial/_basket_row.html' %}
                        </tbody>
                    </table>
                </div>
                <div class="purchase-data">
                    <div class="delivery">
                        Доставка:<span class="in-delivery">бесплатно</span>
                    </div>
                    <div class="amount">
                        Сумма:<span class="cost" id="basket-total-price">{{ total_price }} ₽</span>
                    </div>
                </div>
                <div class="btn-center">
                    <a href="{% url 'payment_preparing' %}" class="basket_content-button">Оформить заказ</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/app/brands.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}
    О брендах
{% endblock %}

{% block body_wrapper_begin %}{% endblock %}
{% block body_wrapper_end %}{% endblock %}

{% block main_content %}
    <div class="brands_page-about">
        <div class="brands-wrap">
            <h2>О брендах</h2>
            <div class="brand-item">
                <div class="brand-item-left-side">
                    <img src="{% static 'img/brands_logo-1.png' %}">
                </div>
                <div class="brand-item-right-side">
                    <div class="brand-item-title">
                        <a href="{% url 'alinex' %}">Сухие строительные смеси AlinEX</a>
                    </div>
                    <div class="brand-item-description">
                        Сухие строительные смеси (ССС) AlinEX, появившийся на отечественном рынке более 16 лет назад,
                        были созданы специально для настоящих профессионалов. Область применения сухих строительных
                        смесей AlinEX обширна: выполнение кладочных, штукатурных, облицовочных работ, устройство
                        покрытий полов, заделка стыков, гидроизолирующие работы, теплоизолирующие работы, декоративные
                        работы и т. д. <a href="{% url 'alinex' %}">Читать подробнее</a>
                    </div>
                    <div class="brand-item-owner">
                        Официальный сайт: <a href="http://www.alinex.kz" target="_blank">www.alinex.kz</a>
                    </div>
                </div>
            </div>
            <div class="brand-item">
                <div class="brand-item-left-side">
                    <img src="{% static 'img/brands_logo-3.png' %}">
                </div>
                <div class="brand-item-right-side">
                    <div class="brand-item-title">
                        <a href="{% url 'alina_paint' %}">Лакокрасочная продукция «Alina Paint»</a>
                    </div>
                    <div class="brand-item-description">
                        Бренд Alina Paint на рынке уже 12 лет, и является одним из старейших брендов Промышленной Группы
                        «Alina». Alina Paint дарит миру цветные всплески, такие яркие, что в любую погоду поднимается
                        настроение, в душе селится радость, и каждый чувствует, что может преобразить к лучшему всю свою
                        жизнь. Вспомните, какое это прекрасное чувство – любоваться только что окрашенной стеной,
                        комнатой, домом. Ведь раскрашивая мир вокруг себя во все цвета радуги, все мы становимся немного
                        волшебниками, не так ли? <a href="{% url 'alina_paint' %}">Читать подробнее</a>
                    </div>
                    <div class="brand-item-owner">
                        Официальный сайт: <a href="http://www.alinapaint.kz" target="_blank">www.alinapaint.kz</a>
                    </div>
                </div>
            </div>
            <div class="brand-item">
                <div class="brand-item-left-side">
                    <img src="{% static 'img/brands_logo-2.png' %}">
                </div>
                <div class="brand-item-right-side">
                    <div class="brand-item-title">
                        <a href="{% url 'nashi' %}">Сухие строительные смеси НАШИ</a>
                    </div>
                    <div class="brand-item-description">
                        Сухие строительные смеси НАШИ – это качественные сухие строительные смеси с необходимым набором
                        свойств, для экономичного ремонта и отделки. В основе философии бренда лежит посыл
                        демократичности, качества и доступности выпускаемой продукции. Именно поэтому графическое
                        оформление бренда и текстовые платформы создаются через призму «общения на равных». <a href="{% url 'nashi' %}">Читать
                        подробнее</a>
                    </div>
                    <div class="brand-item-owner">
                        Официальный сайт: <a href="http://www.nashi-sss.kz" target="_blank">www.nashi-sss.kz</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block footer_content %}
{% endblock %}

templates/app/calculator.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}Калькулятор{% endblock %}
{% block catalog_menu %}
    <div class="catalog-menu">
        <div class="wrapper">
            <nav class="side_megamenu">

            </nav>
            <input type="checkbox" id="sidebartoggler">

            <div class="page-wrap">
                <label for="sidebartoggler" class="toggle">☰</label>

                <div class="page-content">
                    <header></header>
                </div>
                <div class="sidebar">
                    <div class="catalog-mob">
                        <h2>Каталог</h2>
                        {% include "app/partial/_category_list.html" %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block main_content %}
    <div class="main-content">
        <div class="wrapper clearfix">
            <div class="sidebar-main">
                <div class="catalog">
                    <h2>Каталог</h2>
                    {% include 'app/partial/_category_list.html' %}
                </div>
            </div>
            <div class="calculation-main">
                <h2>Штукатурки</h2>
                <div class="calculation-product">
                    <h3>Что вы планируете делать?</h3>
                    <form action="{% url 'calculator' category_id=category_id %}" method="POST" id="calculator-form">
                        {% csrf_token %}
{#                        <div class="select_option">#}
{#                            <div class="select_option-item">#}
{#                                <p><select name="hero">#}
{#                                    <option value="t1" selected>Покрытие лаком</option>#}
{#                                    <option value="t2">Покрытие лаком</option>#}
{#                                    <option value="t3">Покрытие лаком</option>#}
{#                                    <option value="t4">Покрытие лаком</option>#}
{#                                </select></p>#}
{#                            </div>#}
{#                            <div class="select_option-item">#}
{#                                <p><select name="hero">#}
{#                                    <option value="t1" selected>Полуматовый</option>#}
{#                                    <option value="t2">Покрытие лаком</option>#}
{#                                    <option value="t3">Покрытие лаком</option>#}
{#                                    <option value="t4">Покрытие лаком</option>#}
{#                                </select></p>#}
{#                            </div>#}
{#                            <div class="select_option-item">#}
{#                                <p><select name="hero">#}
{#                                    <option value="t1" selected>1 слой</option>#}
{#                                    <option value="t2">Покрытие лаком</option>#}
{#                                    <option value="t3">Покрытие лаком</option>#}
{#                                    <option value="t4">Покрытие лаком</option>#}
{#                                </select></p>#}
{#                            </div>#}
{#                        </div>#}
                        <div class="date-calculate">
                            <div class="date-calculate-item after">
                                <label for="width">Длина</label>
{#                                <input type="number" id="width" placeholder=""><span>м</span>#}
                                {% render_field calculating_form.length type='number' placeholder='' %}<span>м</span>
                            </div>
                            <div class="date-calculate-item after ">
                                <label for="breadth">Ширина</label>
{#                                <input type="number" id="breadth" placeholder=""><span>м</span>#}
                                {% render_field calculating_form.weight type='number' placeholder='' %}<span>м</span>
                            </div>
                            <div class="date-calculate-item">
                                <label for="height">Высота</label>
{#                                <input type="number" id="height" placeholder=""><span>м</span>#}
                                {% render_field calculating_form.height type='number' placeholder='' %}<span>м</span>
                            </div>
                            <span class="and-c">—  ИЛИ — </span>
                            <div class="date-calculate-item">
                                <label for="area">Площадь</label>
{#                                <input type="number" id="area" placeholder=""><span class="sq">м <sup>2</sup></span>#}
                                {% render_field calculating_form.total_sum type='number' placeholder='' %}<span class="sq">м <sup>2</sup></span>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="calculation_main-product">
                    {% include 'app/partial/_trade_list.html' %}
                </div>
            </div>
        </div>
    </div>
    {% include "app/partial/_hidden_elements.html" %}
{% endblock %}

{% block custom_scripts %}
    {{ block.super }}
    <script>
        var widthInput = $('#id_length');
        var weightInput = $('#id_weight');
        var heightInput = $('#id_height');
        var areaInput = $('#id_total_sum');
        var form = $('#calculator-form');

        $(widthInput).on('input', function (event) {
            $(this).trigger('change');
        });
        $(weightInput).on('input', function (event) {
            $(this).trigger('change');
        });
        $(heightInput).on('input', function (event) {
            $(this).trigger('change');
        });
        $(areaInput).on('input', function (event) {
            $(this).trigger('change');
        });

        $(widthInput).on('change', function (event) {
            if($(weightInput).val() != 0) {
                var result = $(this).val() * $(weightInput).val();
                $(areaInput).val(result);
            }
        });

        $(weightInput).on('change', function (event) {
            if($(widthInput).val() != 0) {
                var result = $(this).val() * $(widthInput).val();
                $(heightInput).val('');
                $(areaInput).val(result);
            }
        });

        $(heightInput).on('change', function (event) {
            if($(widthInput).val() != 0) {
                var result = $(this).val() * $(widthInput).val();
                $(weightInput).val('');
                $(areaInput).val(result);
            }
        });

        $(areaInput).on('change', function (event) {
            $(widthInput).val('');
            $(weightInput).val('');
            $(heightInput).val('');
            $(form).submit();
        });

        function updateCalculatingFilters(areaValue) {
            $.ajax({
                url: '{% url 'calculator' category_id=category_id %}',
                method: 'POST',
                dataType: 'JSON',
                data: {'csrfmiddlewaretoken': csrfMiddleWareToken, 'area_value': areaValue},
                success: function (response) {

                },
                error: function () {
                    console.error('Error to update calculating filters');
                }
            });
        }

    </script>
{% endblock %}

templates/app/category.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load webshop %}
{% load widget_tweaks %}

{% block title %}{{ category }}{% endblock %}

{% block catalog_menu %}
    <div class="catalog-menu">
        <div class="wrapper">
            <nav class="side_megamenu">

            </nav>
            <input type="checkbox" id="sidebartoggler">

            <div class="page-wrap">
                <label for="sidebartoggler" class="toggle">☰</label>

                <div class="page-content">
                    <header></header>
                </div>
                <div class="sidebar">
                    <div class="catalog-mob">
                        <h2>Каталог</h2>
                        {% include "app/partial/_category_list.html" %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block main_content %}
    <div class="brands">
        <div class="br-text">
            <p class="br-description ">
                Мы являемся официальными дистрибьюторами, <br/>
                на территоррии РФ, продукции под брендами:
            </p>
        </div>
        <div class="brands-logo">
            <ul>
                <li><a href="{% url 'alinex' %}"><img src="{% static 'img/brands_logo-1.png' %}" alt=""></a></li>
                <li><a href="{% url 'nashi' %}"><img src="{% static 'img/brands_logo-2.png' %}" alt=""></a></li>
                <li><a href="{% url 'alina_paint' %}"><img src="{% static 'img/brands_logo-3.png' %}" alt=""></a></li>
                <li><a href="{% url 'about' %}" class="brands_link-btn">Узнать подробнее<i class="fa fa-chevron-right" aria-hidden="true"></i></a></li>
            </ul>
        </div>
    </div>
    <div class="main-content">
        <div class="wrapper clearfix">
            <div class="sidebar-main">
                <div class="catalog">
                    <h2>Каталог</h2>
                    {% include 'app/partial/_category_list.html' %}
                </div>
            </div>
            <div class="home_main">
                <div class="products_title">
                    <h2>{{ category }}</h2>
                    <p>
                        <strong>{{ category }}</strong>{% if category.description %} - {{ category.description }}{% endif %}
                    </p>
                    <a href="{% url 'calculator' category_id=category.id %}" class="button"><i class="fa fa-calculator" aria-hidden="true"></i> Расчет потребности</a>
                </div>
                <div class="home_products-content">
                    {% include 'app/partial/_trade_list.html' %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/app/contacts.html
{% extends "base.html" %}
{% block title %}
    Контакты
{% endblock %}

{% block body_wrapper_begin %}{% endblock %}
{% block body_wrapper_end %}{% endblock %}

{% block main_content %}
    <div class="about-content">
        <div class="wrapper">
            <div class="about">
                <h1>Контакты</h1>

                <p>
                    {{ content|safe }}
                </p>
            </div>
        </div>
    </div>
{% endblock %}

templates/app/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}
    Главная
{% endblock %}
{% block catalog_menu %}
    <div class="catalog-menu">
        <div class="wrapper">
            <nav class="side_megamenu">

            </nav>
            <input type="checkbox" id="sidebartoggler">

            <div class="page-wrap">
                <label for="sidebartoggler" class="toggle">☰</label>

                <div class="page-content">
                    <header></header>
                </div>
                <div class="sidebar">
                    <div class="catalog-mob">
                        <h2>Каталог</h2>
                        {% include "app/partial/_category_list.html" %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block main_content %}
    <div class="brands">
        <div class="br-text">
            <p class="br-description ">
                Мы являемся официальными дистрибьюторами, <br/>
                на территоррии РФ, продукции под брендами:
            </p>
        </div>
        <div class="brands-logo">
            <ul>
                <li><a href="{% url "alinex" %}"><img src="{% static "img/brands_logo-1.png" %}" alt=""></a></li>
                <li><a href="{% url "nashi" %}"><img src="{% static "img/brands_logo-2.png" %}" alt=""></a></li>
                <li><a href="{% url "alina_paint" %}"><img src="{% static "img/brands_logo-3.png" %}" alt=""></a>
                </li>
                <li><a href="{% url "about" %}" class="brands_link-btn">Узнать подробнее<i
                        class="fa fa-chevron-right"
                        aria-hidden="true"></i>
                </a></li>
            </ul>
        </div>
    </div>
    <div class="main-content">
        <div class="wrapper clearfix">
            <div class="sidebar-main">
                <div class="catalog">
                    <h2>Каталог</h2>
                    {% include "app/partial/_category_list.html" %}
                </div>
            </div>
            <div class="products-main">
                {% if trades_with_discounts %}
                    <h2>Товары по акции</h2>
                    {% include "app/partial/_trade_list_with_discounts.html" %}
                {% endif %}
                <h2>Новые поступления</h2>
                {% include "app/partial/_trade_list.html" %}
                <button id="index-load-button">Ещё товары</button>
            </div>
        </div>
    </div>
    {% include "app/partial/_hidden_elements.html" %}
{% endblock %}

templates/app/news.html
{% extends "base.html" %}
{% block title %}
    Новости
{% endblock %}

{% block body_wrapper_begin %}{% endblock %}
{% block body_wrapper_end %}{% endblock %}

{% block main_content %}
    <div class="about-content">
        <div class="wrapper">
            <div class="about">
                <h1>Новости</h1>


            </div>
        </div>
    </div>
{% endblock %}

templates/app/thanks.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load webshop %}
{% load widget_tweaks %}

{% block title %}Оплата товаров{% endblock %}

{% block body_wrapper_begin %} {% endblock %}
{% block body_wrapper_end %} {% endblock %}

{% block main_content %}
    <div class="payment-content">
        <div class="basket-wrapper">
            <h1>Ваша заявка отправлена!</h1>
            Мы получили заявку, в скором времени с вами свяжутся.
        </div>
    </div>
    {% include 'app/partial/_hidden_elements.html' %}
{% endblock %}

{#{% if has_data %}#}
{#    {% block custom_scripts %}#}
{#        {{ block.super }}#}
{#        <script language="JavaScript" src='https://auth.robokassa.ru/Merchant/PaymentForm/FormFLS.js?MrchLogin=alina_trade&OutSum=1800&InvId="0"&IncCurrLabel=""&Desc="ROBOKASSA Advanced User Guide"&SignatureValue={{ 'alina_trade:1800:0:US1GOa7fEj36WYaeYVU3:Shp_item=1'|encode_value }}&Shp_item="1"&Culture="ru"&Encoding="utf-8"'></script>#}
{#    {% endblock %}#}
{#{% endif %}#}