webshop/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from webshop import settings
from app.views import *

urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^$', index, name='index'),
    url(r'^news$', news, name='news'),
    url(r'^search$', search, name='search'),
    url(r'^about$', about, name='about'),
    url(r'^brands$', brands, name='brands'),
    url(r'^contacts$', contacts, name='contacts'),
    url(r'^alinex$', alinex, name='alinex'),
    url(r'^alinapaint$', alina_paint, name='alina_paint'),
    url(r'^nashi$', nashi, name='nashi'),
    url(r'^trade/(?P<id>\d+)$', trade, name='trade'),
    url(r'^basket$', basket, name='basket'),
    url(r'^basket/add/(?P<trade_id>\d+)$', add_to_basket, name='add_to_basket'),
    url(r'^basket/remove$', remove_from_basket, name='remove_from_basket'),
    url(r'^basket/update/(?P<trade_id>\d+)$', update_basket, name='update_basket'),
    url(r'^basket/all$', list_basket_items, name='list_basket_items'),
    url(r'^basket/clear$', clear_basket, name='clear_basket'),
    url(r'^basket/count/total/price/$', count_basket_cost, name='count_basket_total_price'),
    url(r'^basket/pay/prepare/$', payment_preparing, name='payment_preparing'),
    url(r'^basket/pay/cash/$', pay_money, name='payment_cash'),
    url(r'^basket/pay/result$', payment_preparing, name='payment_preparing'),
    url(r'^calculator/category/(?P<category_id>\d+)/$', calculator, name='calculator'),
    url(r'^category/(?P<category_id>\d+)/$', category, name='category'),
    url(r'^category/(?P<category_id>\d+)/(?P<sub_category_id>\d+)/$', category, name='sub_category'),
    url(r'^misc/trade/add/$', temp_trade_add_view, name='temp_trade_add'),
    url(r'^upload/trade$', upload_trade_data, name='upload_trade_data'),
    url(r'^ajax/index/paginate$', ajax_index_pagination, name='index_paginate'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_models/models.py
# coding=utf-8
from __future__ import unicode_literals
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User as BaseUser
from django.db import models

# Create your models here.


class Category(models.Model):
    class Meta:
        verbose_name_plural = 'Категории'
        verbose_name = 'Категория'

    title = models.CharField(verbose_name='Название', max_length=255, unique=False, null=False)
    parent_category = models.ForeignKey(verbose_name='Родительская категория', to='Category', on_delete=models.CASCADE,
                                        null=True, blank=True)
    type = models.CharField(verbose_name='Раздел категории', choices=(
        ('construction', 'Строительные материалы'), ('decoration', 'Отделочные материалы'),
        ('tools', 'Инструменты')
    ), max_length=255, null=True)
    description = models.CharField(max_length=255, verbose_name='Описание категории', null=True, blank=True)

    created_at = models.DateTimeField(verbose_name='Создано', auto_now_add=True, null=True)
    updated_at = models.DateTimeField(verbose_name='Обновлено', auto_now=True, null=True)

    def __unicode__(self):
        return self.title


class Trade(models.Model):
    class Meta:
        db_table = 'trade'
        verbose_name_plural = 'Товары'
        verbose_name = 'Товар'

    article = models.CharField(verbose_name='Артикул', max_length=255, null=True, blank=True)
    title = models.CharField(verbose_name='Название', max_length=255, unique=False, null=False)
    description = RichTextUploadingField(verbose_name='Описание', null=True, blank=True)
    short_description = RichTextUploadingField(verbose_name='Краткое описание', null=True, blank=True)
    instruction = RichTextUploadingField(verbose_name='Инструкция', null=True, blank=True)
    properties = RichTextUploadingField(verbose_name='Свойства', null=True, blank=True)
    price_settings = models.ManyToManyField('PriceWeight', verbose_name='Цена')
    is_visible = models.BooleanField(verbose_name='Видим?', null=False)
    category = models.ForeignKey(verbose_name='Категория', to=Category, on_delete=models.CASCADE, null=True)
    discount = models.IntegerField(verbose_name='Скидка', default=0)
    image = models.ImageField(verbose_name='Изображение', null=True, blank=True, upload_to='images')
    brand = models.CharField(verbose_name='Бренд', max_length=255, choices=(
        ('alinex', 'Alinex'), ('nashi', 'Наши'), ('alinapaint', 'Alina Paint')
    ), null=True)
    consumption = models.FloatField(verbose_name='Расход (на единицу кв.м.)', default=0)
    layer_weight = models.FloatField(verbose_name='Расходная толщина (мм.)', default=0)
    product_code = models.CharField(verbose_name='Код товара', max_length=255, null=True, blank=True)

    created_at = models.DateTimeField(verbose_name='Создано', auto_now_add=True, null=True)
    updated_at = models.DateTimeField(verbose_name='Об  новлено', auto_now=True, null=True)

    def __unicode__(self):
        return self.title


class User(BaseUser):
    class Meta:
        verbose_name = 'Пользователи'
        verbose_name_plural = 'Пользователи'


class Order(models.Model):
    class Meta:
        verbose_name_plural = 'Заказы'
        verbose_name = 'Заказ'

    elements = models.TextField(verbose_name='Элементы заказа', null=False, default='Заказы:')
    sum = models.FloatField(verbose_name='Сумма', null=False)
    accepted = models.BooleanField(verbose_name='Принято', default=False)
    delivered = models.BooleanField(verbose_name='Доставлено', default=False)
    
    created_at = models.DateTimeField(verbose_name='Создано', auto_now_add=True, null=True)
    updated_at = models.DateTimeField(verbose_name='ОБновлено', auto_now=True, null=True)

    def __unicode__(self):
        return '%s - %s' % (self.user.username, self.sum)


class OrderItem(models.Model):
    class Meta:
        verbose_name_plural = 'Элементы заказов'
        verbose_name = 'Элемент заказа'

    trade = models.ForeignKey(verbose_name='Товар', to=Trade, on_delete=models.CASCADE, null=False)
    quantity = models.IntegerField(verbose_name='Количество', null=False)
    order = models.ForeignKey(verbose_name='Заказ', to=Order, on_delete=models.CASCADE, null=False)
    
    created_at = models.DateTimeField(verbose_name='Создано', auto_now_add=True, null=True)
    updated_at = models.DateTimeField(verbose_name='Обновлено', auto_now=True, null=True)

    def __unicode__(self):
        return '%s - %s' % (self.trade.title, self.quantity)


class News(models.Model):
    class Meta:
        verbose_name_plural = 'Новости'
        verbose_name = 'Новости'

    title = models.CharField(verbose_name='Заголовок', max_length=255, unique=False, null=False)
    description = RichTextUploadingField(verbose_name='Описание категории', null=True, blank=True)
    is_visible = models.BooleanField(verbose_name='Видим?', null=False)
    
    created_at = models.DateTimeField(verbose_name='Создано', auto_now_add=True, null=True)
    updated_at = models.DateTimeField(verbose_name='Обновлено', auto_now=True, null=True)

    def __unicode__(self):
        return self.title


class PriceWeight(models.Model):
    class Meta:
        verbose_name_plural = 'Цены'
        verbose_name = 'Цена'

    weight = models.CharField(verbose_name='Вес', max_length=255, unique=False, null=False)
    price = models.FloatField(verbose_name='Цена', null=False)
    
    created_at = models.DateTimeField(verbose_name='Создано', auto_now_add=True, null=True)
    updated_at = models.DateTimeField(verbose_name='Обновлено', auto_now=True, null=True)

    def __unicode__(self):
        return '%s кг - %s руб' % (self.weight, self.price)


class PageContent(models.Model):
    class Meta:
        db_table = 'page_content'
        verbose_name = 'Редактрование страниц'
        verbose_name_plural = 'Редактирование страниц'

    about = RichTextUploadingField(verbose_name='О нас', null=True, blank=True)
    contacts = RichTextUploadingField(verbose_name='Контакты', null=True, blank=True)
    alinex = RichTextUploadingField(verbose_name='Alinex', null=True, blank=True)
    alina_paint = RichTextUploadingField(verbose_name='Alina Paint', null=True, blank=True)
    nashi = RichTextUploadingField(verbose_name='Nashi', null=True, blank=True)

    def __unicode__(self):
        return 'Редактирование страниц: "О нас", "Контакты" и страница брендов'

templates/app/partial/_basket_elemt.html
{% load webshop %}

{% for row in basket_items %}
    <tr>
        <td>{{ row.title }}</td>
        <td>
            {% if row.weight.all|length > 1 %}
                {% for item in row.weight.all %}
                    {% if item.price == row.price %}{{ item.weight }}{% endif %}
                {% endfor %}
            {% else %}
                <span data-id="{{ row.weight.first.id }}">{{ row.weight.first.weight }} кг</span>
            {% endif %}
        </td>
        <td>
            {{ row.count }}
        </td>
        <td><span>{{ row.price }} RUB</span></td>
    </tr>
{% endfor %}

templates/app/partial/_basket_row.html
{% load webshop %}

{% for row in basket_items %}
    <tr class="product-one" data-update="{% url 'update_basket' trade_id=row.id %}" data-order-number="{{ row.order_number }}">
        <td class="table_title" data-label="НАЗВАНИЕ">{{ row.title }}</td>
        <td class="data-product" data-label="Объем" data-type="{% if row.weight.all|length == 1 %}one{% else %}many{% endif %}">
            {% if row.weight.all|length > 1 %}
                <form action="{% url 'update_basket' trade_id=row.id %}">
                    <div class="weight-paint">
                        <select>
                            {% for item in row.weight.all %}
                                {% if row.product %}
                                    <option value="{{ item.id }}" data-price="{{ item.price|pprint|get_price_with_discount:row.product.discount }}" {% if item.price == row.price %}selected{% endif %}>{{ item.weight }}</option>
                                {% else %}
                                    <option value="{{ item.id }}" data-price="{{ item.price }}" {% if item.price == row.price %}selected{% endif %}>{{ item.weight }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </div>
                </form>
            {% else %}
                <span data-id="{{ row.weight.first.id }}">{{ row.weight.first.weight }} кг</span>
            {% endif %}
        </td>
        <td data-label="Количество" class="row-count">
            <form action="" class="form-popup">
                <input type="number" name="quantity" min="0" max="100" step="1" value="{{ row.count }}"
                       class="quantity-products quant" placeholder="">
                <span class="count_btn">
                    <span class="count-arrow plus">
                        <i class="fa fa-chevron-down  fa-rotate-180"></i>
                    </span>
                    <span class="count-arrow minus">
                        <i class="fa fa-chevron-down"></i>
                    </span>
                </span>
            </form>
        </td>
        <td data-label="Цена" class="row-price"><span>{{ row.price }} ₽</span></td>
        <td>
            <span class="dl_btn">
                <i class="fa fa-times remove-order" aria-hidden="true" data-remove-id="{% url 'remove_from_basket' %}"></i>
            </span>
        </td>
        <td class="min-del" data-label="">удалить товар</td>
    </tr>
{% endfor %}

templates/app/partial/_category_list.html
<div class="building-list">
    <h4>Строительные материалы</h4>
    <nav class="side-nav">
        <ul>
            {% for c in constructions %}
                {% with c.category_set.all as subs %}
                    {% if subs|length > 0 %}
                        <li class="sd_nav-item">
                            <a href="{% url 'category' category_id=c.id %}">{{ c.title }} <i class="fa fa-chevron-down" aria-hidden="true"></i></a>
                            <ul class="submenu">
                                {% for sub in subs %}
                                    <li><a href="{% url 'sub_category' category_id=c.id sub_category_id=sub.id %}">{{ sub.title }}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                    {% else %}
                        <li class="sd_nav-item"><a href="{% url 'category' category_id=c.id %}" >{{ c.title }}</a></li>
                    {% endif %}
                {% endwith %}
            {% endfor %}
        </ul>
    </nav>
</div>
<div class="decoration-list">
    <h4>Отделочные материалы</h4>
    <ul>
        {% for d in decorations %}
            {% with d.category_set.all as subs %}
                {% if subs|length > 0 %}
                    <li class="sd_nav-item"><a href="{% url 'category' category_id=d.title %}">{{ d.title }} <i class="fa fa-chevron-down" aria-hidden="true"></i></a>
                        <ul class="submenu">
                            {% for sub in subs %}
                                <li><a href="{% url 'sub_category' category_id=c.id sub_category_id=sub.id %}">{{ sub.title }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                {% else %}
                    <li class="sd_nav-item"><a href="{% url 'category' category_id=d.id %}">{{ d.title }}</a></li>
                {% endif %}
            {% endwith %}
        {% endfor %}
    </ul>
</div>
<div class="instruments-list">
    <h4>Инструменты</h4>
    <ul>
        {% for t in tools %}
            {% with t.category_set.all as subs %}
                {% if subs|length > 0 %}
                    <li class="sd_nav-item"><a href="{% url 'category' category_id=t.id %}">{{ t.title }} <i class="fa fa-chevron-down" aria-hidden="true"></i></a>
                        <ul class="submenu">
                            {% for sub in subs %}
                                <li><a href="{% url 'sub_category' category_id=t.id sub_category_id=sub.id %}">{{ sub.title }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                {% else %}
                    <li class="sd_nav-item"><a href="{% url 'category' category_id=t.id %}">{{ t.title }}</a></li>
                {% endif %}
            {% endwith %}
        {% endfor %}
    </ul>
</div>

templates/app/partial/_email_order.html
<div class="user-information">
    <b>Имя:</b> {{ name }}<br />
    <b>Телефон: </b> {{ phone }}<br />
    <b>Адрес:</b> {{ address }}<br />
</div>
<table>
    <colgroup>
        <col class="col1">
    </colgroup>
    <thead>
    <tr>
        <th scope="col">Название</th>
        <th scope="col">Объем</th>
        <th scope="col">Количество</th>
        <th scope="col">Цена</th>
    </tr>
    </thead>
    <tbody>
    {% include 'app/partial/_basket_elemt.html' %}
    </tbody>
</table>
<br />
<b>Сумма</b>: {{ total_price }} RUB

templates/app/partial/_hidden_elements.html
<div class="hidden-elements">
    <div class="popup-content">
        <div class="modal-wrapper">
            <div class="modal">
                <div class="content">
                    <div id="popup-products" class="new-table">
                        <table>
                            <colgroup>
                                <col class="col1">
                            </colgroup>
                            <thead>
                            <tr>
                                <th scope="col">Название</th>
                                <th scope="col">Объем</th>
                                <th scope="col">Количество</th>
                                <th scope="col">Цена</th>
                            </tr>
                            </thead>
                            <tbody class="basket-rows">
                            {% include 'app/partial/_basket_row.html' %}
                            </tbody>
                        </table>
                    </div>
                    <div class="footer-popup">
                        <a href="" class="btn-close trigger">Закрыть</a>
                        <a href="{% url 'basket' %}" class="btn-link">Показать корзину</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/app/partial/_order_template.html
<style>
    .new-table table {
    border: 1px solid #ccc;
    border-collapse: collapse;
    margin: 0;
    padding: 0;
    width: 100%;
    table-layout: fixed;
}

    .new-table table caption {
    font-size: 1.5em;
    margin: .5em 0 .75em;
    }

    .new-table table thead th {
        font-family: "RobotoRegular", sans-serif;
        font-size: 16px;
        font-weight: bold;
        width: 100%;
        height: 30px;
        color: #666666;
        background: #F6F6F6;
        border: 1px solid #e6e6e5;
    }

    .new-table table tr {
        padding: .35em;
        background: #f8f8f8;
        border: 1px solid #ddd;
    }

    .new-table table td:first-child {
        font-size: 18px;
        cursor: default;
        text-align: left;
    }

    .new-table table {
        font-family: "RobotoLight", sans-serif;
        font-size: 20px;
        color: #333333;
    }

    .new-table table th,
    .new-table table td {
        height: 60px;
        padding: 8px 24px;
        text-align: center;
        background: #FFFFFF;
        border: 1px solid #e6e6e6;

    }

    .new-table table th {
        font-size: 16px;
        letter-spacing: .1em;
    }

    .new-table table td span {
        display: block;
    }

    .new-table .col1 {
        width: 362px;
        text-align: left;
        letter-spacing: 0;
    }
</style>

<div class="basket-main">
    <div class="new-table">
        <table>
            <colgroup>
                <col class="col1">
            </colgroup>
            <thead>
            <tr>
                <th scope="col">Название</th>
                <th scope="col">Объем</th>
                <th scope="col">Количество</th>
                <th scope="col">Цена</th>
            </tr>
            </thead>
            <tbody>
            {% include 'app/partial/_basket_row.html' %}
            </tbody>
        </table>
    </div>
    <div class="purchase-data">
        <div class="delivery">
            Доставка:<span class="in-delivery">бесплатно</span>
        </div>
        <div class="amount">
            Сумма:<span class="cost" id="basket-total-price">{{ total_price }} ₽</span>
        </div>
    </div>
</div>

templates/app/partial/_trade_list.html
{% load staticfiles %}
{% load webshop %}

<div class="new-products">
    {% for trade in new_trades %}
        {% with trade.price_settings.all as price_settings %}
            {% if price_settings|length == 1 %}
                <div class="{% if trade.discount > 0 %}sale-product{% else %}product{% endif %} product-item"
                     data-date="{{ trade.created_at|date:'Y-m-d' }}"
                     data-price="{{ price_settings.0.price|get_price_with_discount:trade.discount }}"
                     data-direction="desc">
                    {% if trade.discount > 0 %}
                        <div class="sale-w">{{ trade.discount }}%</div>
                    {% endif %}
                    <a href="{% url 'trade' id=trade.id %}">
                        <div class="pr-elements">
                            <img src="{{ trade.image.url }}" alt="{{ trade.title }}">
                        </div>
                    </a>
                    <div class="pr-title">
                        <a href="{% url "trade" id=trade.id %}">
                            <h4>{% if trade.title|length >= 26 %}{{ trade.title|slice:'0:23' }}...{% else %}{{ trade.title }}{% endif %}</h4>
                        </a>
                    </div>
                    {% if trade.discount > 0 %}
                        <span class="sale-price">
                            {{ price_settings.0.price|get_price_with_discount:trade.discount }} ₽
                        </span>
                    {% endif %}
                    <span class="{% if trade.discount > 0 %}line-through-price{% else %}price{% endif %}">{{ price_settings.0.price }} ₽</span>
                    <span class="weight" data-id="{{ price_settings.0.id }}">{{ price_settings.0.weight }} кг</span>

                    <form class="pr-form">
                        <input type="number" name="quantity" min="0" step="1" value="{% if trade.item_count %}{{ trade.item_count }}{% else %}1{% endif %}" class="quantity-products" placeholder="">
                        <span class="count_btn">
                            <span class="count-arrow plus">
                                <i class="fa fa-chevron-down  fa-rotate-180"></i>
                            </span>
                            <span class="count-arrow minus">
                                <i class="fa fa-chevron-down"></i>
                            </span>
                        </span>
                        <a href="" class="button trigger" data-target="{% url 'add_to_basket' trade_id=trade.id %}" data-type="{% if price_settings|length == 1 %}one{% else %}many{% endif %}">Добавить в корзину</a>
                    </form>
                </div>
            {% elif price_settings|length > 1 %}
                <div class="paints-product product-item"
                     data-date="{{ trade.created_at|date:'Y-m-d' }}"
                     data-price="{{ price_settings.0.price|get_price_with_discount:trade.discount }}"
                     data-direction="desc">
                    {% if trade.discount > 0 %}
                        <div class="sale-w">{{ trade.discount }}%</div>
                    {% endif %}
                    <div class="pr-elements">
                        <img src="{{ trade.image.url }}" alt="{{ trade.title }}">
                    </div>
                    <div class="pr-title">
                        <a href="{% url "trade" id=trade.id %}">
                            <h4>{% if trade.title|length > 26 %}{{ trade.title|slice:'0:23' }}...{% else %}{{ trade.title }}{% endif %}</h4>
                        </a>
                    </div>
                    {% if trade.discount > 0 %}
                        <span class="sale-price">
                            {{ price_settings.0.price|get_price_with_discount:trade.discount }} ₽
                        </span>
                    {% endif %}
                    <span class="{% if trade.discount > 0 %}line-through-price{% else %}price{% endif %}">{{ price_settings.0.price }} ₽</span>

                    <div class="weight-paint">
                        <select>
                            {% for ps in price_settings %}
                                <option data-price="{{ ps.price }}" value="{{ ps.id }}">{{ ps.weight }} кг</option>
                            {% endfor %}
                        </select>
                    </div>
                    <form class="pr-form">
                        <input type="number" name="quantity" min="0" step="1" value="{% if trade.item_count %}{{ trade.item_count }}{% else %}1{% endif %}" class="quantity-products" placeholder="">
                        <span class="count_btn">
                            <span class="count-arrow plus">
                                <i class="fa fa-chevron-down  fa-rotate-180"></i>
                            </span>
                            <span class="count-arrow minus">
                                <i class="fa fa-chevron-down"></i>
                            </span>
                        </span>
                        <a href="" class="button trigger" data-target="{% url 'add_to_basket' trade_id=trade.id %}" data-type="{% if price_settings|length == 1 %}one{% else %}many{% endif %}">Добавить в корзину</a>
                    </form>
                </div>
            {% endif %}
        {% endwith %}
    {% endfor %}
</div>

templates/app/partial/_trade_list_with_discounts.html
{% load staticfiles %}
{% load webshop %}

<div class="sale">
    {% for trade in trades_with_discounts %}
        {% with trade.price_settings.all as price_settings %}
            {% if price_settings|length == 1 %}
                <div class="sale-product">
                    <div class="sale-w">{{ trade.discount }}%</div>
                    <a href="{% url 'trade' id=trade.id %}">
                        <div class="pr-elements">
                            <img src="{{ trade.image.url }}" alt="{{ trade.title }}">
                        </div>
                    </a>
                    <div class="pr-title">
                        <a href="{% url "trade" id=trade.id %}">
                            <h4>{% if trade.title|length >= 26 %}{{ trade.title|slice:'0:23' }}...{% else %}{{ trade.title }}{% endif %}</h4>
                        </a>
                    </div>
                    <span class="sale-price">
                        {{ price_settings.0.price|get_price_with_discount:trade.discount }} ₽
                    </span>
                    <span class="price">{{ price_settings.0.price }} ₽</span>
                    <span class="weight" data-id="{{ price_settings.0.id }}">{{ price_settings.0.weight }} кг</span>

                    <form class="pr-form">
                        <input type="number" name="quantity" min="0" max="100" step="1" value="1" class="quantity-products" placeholder="">
                                    <span class="count_btn">
                                            <span class="count-arrow plus">
                                                <i class="fa fa-chevron-down  fa-rotate-180"></i>
                                            </span>
                                            <span class="count-arrow minus">
                                                <i class="fa fa-chevron-down"></i>
                                            </span>
                                    </span>
                        <a href="" class="button trigger" data-target="{% url 'add_to_basket' trade_id=trade.id %}" data-type="{% if price_settings|length == 1 %}one{% else %}many{% endif %}">Добавить в корзину</a>
                    </form>
                </div>
            {% elif price_settings|length > 1 %}
                <div class="paints-product">
                    <div class="sale-w">{{ trade.discount }}%</div>
                    <a href="{% url 'trade' id=trade.id %}">
                        <div class="pr-elements">
                            <img src="{{ trade.image.url }}" alt="{{ trade.title }}">
                        </div>
                    </a>
                    <div class="pr-title">
                        <a href="{% url "trade" id=trade.id %}">
                            <h4>{% if trade.title|length >= 26 %}{{ trade.title|slice:'0:23' }}...{% else %}{{ trade.title }}{% endif %}</h4>
                        </a>
                    </div>
                    <span class="sale-price">
                        {{ price_settings.0.price|get_price_with_discount:trade.discount }} ₽
                    </span>
                    <span class="price">{{ price_settings.0.price }} ₽</span>

                    <div class="weight-paint">
                        <select>
                            {% for ps in price_settings %}
                                <option data-price="{{ ps.price }}" value="{{ ps.id }}">{{ ps.weight }} кг</option>
                            {% endfor %}
                        </select>
                    </div>
                    <form class="pr-form">
                        <input type="number" name="quantity" min="0" max="100" step="1" value="1" class="quantity-products" placeholder="">
                                    <span class="count_btn">
                                            <span class="count-arrow plus">
                                                <i class="fa fa-chevron-down  fa-rotate-180"></i>
                                            </span>
                                            <span class="count-arrow minus">
                                                <i class="fa fa-chevron-down"></i>
                                            </span>
                                    </span>
                        <a href="" class="button trigger" data-target="{% url 'add_to_basket' trade_id=trade.id %}" data-type="{% if price_settings|length == 1 %}one{% else %}many{% endif %}">Добавить в корзину</a>
                    </form>
                </div>
            {% endif %}
        {% endwith %}
    {% endfor %}
</div>